AWSTemplateFormatVersion: "2010-09-09"
Resources:

  # Definición de las instancias EC2
  EC2InstanceDev:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: "t2.medium"
      ImageId: "ami-01eed4fd757780e33"
      KeyName: "vockey"  # Cambia esto por el nombre de tu clave
      Tags:
        - Key: "Name"
          Value: "MV_Ciencia_Datos_dev"
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup

  EC2InstanceTest:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: "t2.medium"
      ImageId: "ami-01eed4fd757780e33"
      KeyName: "vockey"  # Cambia esto por el nombre de tu clave
      Tags:
        - Key: "Name"
          Value: "MV_Ciencia_Datos_test"
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup

  EC2InstanceProd:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: "t2.medium"
      ImageId: "ami-01eed4fd757780e33"
      KeyName: "vockey"  # Cambia esto por el nombre de tu clave
      Tags:
        - Key: "Name"
          Value: "MV_Ciencia_Datos_prod"
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup

  # Definición del bucket S3 para Dev
  S3BucketDev:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "ciencia-datos-bucket-rockie-dev"  # Cambia esto por el nombre único de tu bucket
      Tags:
        - Key: "Name"
          Value: "CienciaDatosBucketDev"

  # Definición del bucket S3 para Test
  S3BucketTest:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "ciencia-datos-bucket-rockie-test"  # Cambia esto por el nombre único de tu bucket
      Tags:
        - Key: "Name"
          Value: "CienciaDatosBucketTest"

  # Definición del bucket S3 para Prod
  S3BucketProd:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "ciencia-datos-bucket-rockie-prod"  # Cambia esto por el nombre único de tu bucket
      Tags:
        - Key: "Name"
          Value: "CienciaDatosBucketProd"

  GlueDatabaseDev:
    Type: "AWS::Glue::Database"
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: "rockie_database_dev"

  GlueDatabaseTest:
    Type: "AWS::Glue::Database"
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: "rockie_database_test"

  GlueDatabaseProd:
    Type: "AWS::Glue::Database"
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: "rockie_database_prod"

  InstanceSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Abrir puertos para base de datos y Adminer"
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: "22"
          ToPort: "22"
          CidrIp: "0.0.0.0/0"
        - IpProtocol: "tcp"
          FromPort: "8005"
          ToPort: "8005"
          CidrIp: "0.0.0.0/0"
        - IpProtocol: "tcp"
          FromPort: "8080"
          ToPort: "8080"

Outputs:
  EC2InstanceDevID:
    Description: "ID de la instancia EC2 para dev"
    Value: !Ref EC2InstanceDev

  EC2InstanceTestID:
    Description: "ID de la instancia EC2 para test"
    Value: !Ref EC2InstanceTest

  EC2InstanceProdID:
    Description: "ID de la instancia EC2 para prod"
    Value: !Ref EC2InstanceProd

  S3BucketNameDev:
    Description: "Nombre del bucket S3 para Dev"
    Value: !Ref S3BucketDev

  S3BucketNameTest:
    Description: "Nombre del bucket S3 para Test"
    Value: !Ref S3BucketTest

  S3BucketNameProd:
    Description: "Nombre del bucket S3 para Prod"
    Value: !Ref S3BucketProd
